//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendedor()
        {
            this.Activo = new HashSet<Activo>();
        }


        [Display(Name = "Cédula Jurídica")]
        [Required(ErrorMessage = "{0} es un dato requerido")]
        [MaxLength(50, ErrorMessage = "La {0} debe ser máximo {1} caracteres")]
        public string CedulaJuridica { get; set; }


  
        [Required(ErrorMessage = "{0} es un dato requerido")]
        [MaxLength(30, ErrorMessage = "El {0} debe ser máximo {1} caracteres")]
        public string Ente { get; set; }


        [Display(Name = "Correo electrónico")]
        [DataType(DataType.EmailAddress, ErrorMessage ="El formato no es el correcto.")]
        [MaxLength(30, ErrorMessage = "El {0} debe ser máximo {1} caracteres")]
        public string Email { get; set; }

        [Phone]
        [Display(Name = "Teléfono")]
        [MaxLength(8,ErrorMessage = "El {0} debe ser máximo {1} dígitos")]
        public string Telefono { get; set; }


        [Display(Name ="Dirección")]
        [MaxLength(100, ErrorMessage = "La {0} debe ser máximo {1} caracteres")]
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activo> Activo { get; set; }
    }
}
